sleuth:
    sampler:
      percentage: 1.0
spring:
  cloud:
    stream:
      kafka:
        binder:
          zk-nodes: 172.30.150.26:2181
          brokers: 172.30.150.26:9092
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://172.30.150.60:60702/eureka/
management:
  security:
    enabled: false
